apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage
  namespace: llama-cpp
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
