apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache
  namespace: llama-cpp
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
