apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rpc-worker
  namespace: llama-cpp
  annotations:
    service-per-pod-label: statefulset.kubernetes.io/pod-name
    service-per-pod-ports: "50052"
spec:
  serviceName: rpc-worker-headless
  replicas: 3
  selector:
    matchLabels:
      app: rpc-worker
  template:
    metadata:
      labels:
        app: rpc-worker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - talos-0u4-tjd
                - talos-q0c-o34
                - talos-u79-gei
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: rpc-worker
            topologyKey: kubernetes.io/hostname
      containers:
      - name: rpc-server
        image: ogmiladyloki/llama-cpp-rpc-server:latest
        imagePullPolicy: Always
        command: ["rpc-server", "-H", "0.0.0.0", "-p", "50052"]
        ports:
        - containerPort: 50052
          name: rpc
        resources:
          requests:
            cpu: "1"
            memory: 2Gi
