apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: service-per-pod
  namespace: metacontroller
spec:
  resources:
  - apiVersion: apps/v1
    resource: statefulsets
    annotationSelector:
      matchExpressions:
      - key: service-per-pod-label
        operator: Exists
      - key: service-per-pod-ports
        operator: Exists
  attachments:
  - apiVersion: v1
    resource: services
  hooks:
    sync:
      webhook:
        url: http://service-per-pod-controller.metacontroller/sync
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-per-pod-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-per-pod-controller
  template:
    metadata:
      labels:
        app: service-per-pod-controller
    spec:
      containers:
      - name: jsonnetd
        image: metacontroller/jsonnetd:0.1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: hooks
          mountPath: /hooks
          readOnly: true
      volumes:
      - name: hooks
        configMap:
          name: service-per-pod-controller
---
apiVersion: v1
kind: Service
metadata:
  name: service-per-pod-controller
  namespace: metacontroller
spec:
  selector:
    app: service-per-pod-controller
  ports:
  - port: 80
    targetPort: 8080
