pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/miladyos.crt
  key: /etc/nebula/miladyos.key

static_host_map:
  "192.168.5.1": ["34.42.134.173:4242"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "192.168.5.1"

listen:
  host: 0.0.0.0
  port: 4242

punchy:
  punch: true

tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300

logging:
  level: info
  format: text

firewall:
  outbound:
    - port: any
      proto: any
      host: any
  inbound:
    - port: any
      proto: any
      host: any