apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      nodeSelector:
        kubernetes.io/hostname: talos-o5y-af4
      containers:
      - name: runner
        image: myoung34/github-runner:latest
        env:
        - name: REPO_URL
          value: "https://github.com/theycallmeloki/MiladyOS"
        - name: RUNNER_NAME
          value: "miladyos-builder"
        - name: RUNNER_LABELS
          value: "self-hosted,linux"
        - name: ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-runner-pat
              key: GITHUB_PAT
        - name: RUNNER_WORKDIR
          value: "/home/runner/_work"
        - name: DOCKER_HOST
          value: "tcp://localhost:2375"
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: "40"
            memory: "160Gi"
          requests:
            cpu: "4"
            memory: "16Gi"
        volumeMounts:
        - name: runner-data
          mountPath: /home/runner/_work
      # Add Docker-in-Docker sidecar
      - name: dind
        image: docker:dind
        securityContext:
          privileged: true
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
        volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
      volumes:
      - name: runner-data
        emptyDir: {}
      - name: dind-storage
        emptyDir: {}