apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- rlmjob-crd.yaml
- composite-controller.yaml
- webhook-deployment.yaml
- rlm-rbac.yaml
- webhook-sync-hook-configmap.yaml
- coordinator-configmap.yaml
- rlm-logs-pvc.yaml
- rlm-visualizer-deployment.yaml
