apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rlm-logs
  namespace: rlm-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
