apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatus-data
  namespace: default
spec:
  storageClassName: longhorn-single-replica
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi