apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autodidact-data-v2
  namespace: autodidact
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-single-replica
  resources:
    requests:
      storage: 50Gi