apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache
  namespace: self-hosted-models
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
