apiVersion: v1
kind: ServiceAccount
metadata:
  name: pachyderm
  namespace: pachyderm
  labels:
    suite: pachyderm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pachyderm-worker
  namespace: pachyderm
  labels:
    suite: pachyderm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pachyderm
  labels:
    suite: pachyderm
rules:
- apiGroups: [""]
  resources: [nodes, pods, pods/log, endpoints]
  verbs: [get, list, watch]
- apiGroups: [""]
  resources: [replicationcontrollers, services]
  verbs: [get, list, watch, create, update, delete]
- apiGroups: [""]
  resources: [secrets]
  verbs: [get, list, watch, create, update, delete, deletecollection]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pachyderm
  labels:
    suite: pachyderm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pachyderm
subjects:
- kind: ServiceAccount
  name: pachyderm
  namespace: pachyderm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pachyderm-worker
  namespace: pachyderm
  labels:
    suite: pachyderm
rules:
- apiGroups: [""]
  resources: [services]
  verbs: [get, list, update, create, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pachyderm-worker
  namespace: pachyderm
  labels:
    suite: pachyderm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pachyderm-worker
subjects:
- kind: ServiceAccount
  name: pachyderm-worker
  namespace: pachyderm
