apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-smi-exporter
  namespace: monitoring
  labels:
    app: nvidia-smi-exporter
spec:
  selector:
    matchLabels:
      app: nvidia-smi-exporter
  template:
    metadata:
      labels:
        app: nvidia-smi-exporter
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        nvidia.com/gpu.present: "true"
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      containers:
      - name: exporter
        image: utkuozdemir/nvidia_gpu_exporter:1.2.1
        ports:
        - name: metrics
          containerPort: 9835
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "utility"
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
