apiVersion: v1
kind: Service
metadata:
  name: nvidia-smi-exporter
  namespace: monitoring
  labels:
    app: nvidia-smi-exporter
spec:
  selector:
    app: nvidia-smi-exporter
  ports:
  - name: metrics
    port: 9835
    targetPort: 9835
