apiVersion: v1
kind: Service
metadata:
  name: ups-server
  namespace: monitoring
  labels:
    app: ups-server
spec:
  selector:
    app: ups-server
  ports:
  - name: nut
    port: 3493
    targetPort: 3493
  type: ClusterIP