apiVersion: v1
kind: Service
metadata:
  name: ups-exporter
  namespace: monitoring
  labels:
    app: ups-exporter
spec:
  selector:
    app: ups-exporter
  ports:
  - name: metrics
    port: 9099
    targetPort: 9099
  type: ClusterIP