apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-agent
  namespace: fleet-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleet-agent
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "services", "namespaces", "persistentvolumeclaims",
               "configmaps", "events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["argoproj.io"]
  resources: ["applications"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fleet-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fleet-agent
subjects:
- kind: ServiceAccount
  name: fleet-agent
  namespace: fleet-agent
