apiVersion: v1
kind: Service
metadata:
  name: fleet-agent-webhook
  namespace: fleet-agent
  labels:
    app: fleet-agent
    app.kubernetes.io/part-of: miladyos
spec:
  selector:
    app: fleet-agent
  ports:
    - name: webhook
      port: 9000
      targetPort: 9000
