apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fleet-agent-data
  namespace: fleet-agent
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
