apiVersion: v1
kind: ConfigMap
metadata:
  name: ha-configuration
  namespace: homeassistant
data:
  configuration.yaml: |
    # Configure a default setup of Home Assistant
    default_config:

    # Text to speech
    tts:
      - platform: google_translate
    
    # Use SQLite for now to get the system running
    recorder:
      db_url: sqlite:///config/home-assistant_v2.db
      
    # WiZ Smart Plug integration
    wiz:
      discovery: true
    
    # Power monitoring sensors
    sensor:
      - platform: wiz_power_monitoring
    
    # Enhanced HTTP configuration
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 127.0.0.1
        - ::1
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16