apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: talos-4vi-s4q
      initContainers:
      - name: volume-permissions
        image: busybox
        securityContext:
          privileged: true
        command: 
        - sh
        - -c
        - |
          mkdir -p /config
          chown -R 0:0 /config
          chmod -R 775 /config
          ls -la /config
        volumeMounts:
        - mountPath: /config
          name: homeassistant
      containers:
      - image: ghcr.io/home-assistant/home-assistant:latest
        imagePullPolicy: Always
        name: homeassistant
        securityContext:
          allowPrivilegeEscalation: true
          runAsUser: 0
          privileged: true
        ports:
        - containerPort: 8123
          name: web
          protocol: TCP
        env:
        - name: TZ
          value: Europe/London
        volumeMounts:
        - mountPath: /config
          name: homeassistant
        - mountPath: /config/configuration.yaml
          subPath: configuration.yaml
          name: ha-config
      volumes:
        - name: homeassistant
          persistentVolumeClaim:
            claimName: homeassistant
        - name: ha-config
          configMap:
            name: ha-configuration
            defaultMode: 0644