apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant
  namespace: homeassistant
  annotations:
    volume.kubernetes.io/selected-node: talos-4vi-s4q
spec:
  storageClassName: longhorn-single-replica
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi