apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-ingress
  namespace: homeassistant
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "homeassistant"
spec:
  ingressClassName: nginx
  rules:
  - host: ha.transparentlyrotatableproxy.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homeassistant
            port:
              number: 8123
  tls:
  - hosts:
    - ha.transparentlyrotatableproxy.site
    secretName: ha-transparentlyrotatableproxy-me-tls
