apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tuya-exporter
  namespace: monitoring
  labels:
    app: tuya-exporter
    release: prometheus # This must match your Prometheus Operator release label
spec:
  selector:
    matchLabels:
      app: tuya-exporter
  endpoints:
  - port: metrics
    interval: 60s
  namespaceSelector:
    matchNames:
    - monitoring