apiVersion: v1
kind: Service
metadata:
  name: tuya-exporter
  namespace: monitoring
  labels:
    app: tuya-exporter
spec:
  selector:
    app: tuya-exporter
  ports:
  - name: metrics
    port: 9089
    targetPort: 9089
  type: ClusterIP