apiVersion: v1
kind: ConfigMap
metadata:
  name: snmp-exporter-config
  namespace: monitoring
data:
  snmp.yml: |
    auths:
      tplink_v3:
        version: 3
        security_level: authPriv
        username: milady_snmp
        password: SecureMiladyPassword
        auth_protocol: SHA
        priv_protocol: AES
        priv_password: SecureMiladyPassword
      public_v2:
        version: 2
        community: public
    
    modules:
      tplink:
        walk:
          - 1.3.6.1.2.1.1
          - 1.3.6.1.2.1.2
          - 1.3.6.1.2.1.31.1.1
      if_mib:
        walk:
          - 1.3.6.1.2.1.1
          - 1.3.6.1.2.1.2
          - 1.3.6.1.2.1.31.1.1