apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwq-32b
  namespace: default
  labels:
    app: qwq-32b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwq-32b
  template:
    metadata:
      labels:
        app: qwq-32b
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        kubernetes.io/hostname: talos-dkp-mps
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - qwq-32b
            topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: qwq-32b
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: "8Gi"
      - name: dev
        hostPath:
          path: /dev
      containers:
      - name: qwq-32b
        image: vllm/vllm-openai:latest
        command: ["/bin/sh", "-c"]
        args: [
          "vllm serve Qwen/QwQ-32B-AWQ --trust-remote-code --tensor-parallel-size 2 --max-model-len 32768 --swap-space 4 --max-num-batched-tokens 8192 --max-num-seqs 256 --enforce-eager --disable-custom-all-reduce --device cuda --gpu-memory-utilization 0.85 --quantization awq --dtype auto --host 0.0.0.0 --port 8000"
        ]
        env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token-secret
              key: token
              optional: true
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: VLLM_LOGGING_LEVEL
          value: "DEBUG"
        - name: TRANSFORMERS_CACHE
          value: "/root/.cache/huggingface/hub"
        - name: HF_HOME
          value: "/root/.cache/huggingface"
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "8"
            memory: 16G
            nvidia.com/gpu: "2"
          requests:
            cpu: "4"
            memory: 8G
            nvidia.com/gpu: "2"
        volumeMounts:
        - mountPath: /root/.cache
          name: cache-volume
        - name: shm
          mountPath: /dev/shm
        - name: dev
          mountPath: /dev
        securityContext:
          privileged: true
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 600
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 600
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3