apiVersion: v1
kind: Secret
metadata:
  name: vault-mongodb-credentials
  namespace: vault
type: Opaque
stringData:
  connection-string: "mongodb+srv://ogmiladyloki:r1cDzliILcgFiMkR@miladyos-production.jvphptl.mongodb.net/?retryWrites=true&w=majority&appName=miladyos-production"
  database: "vault-storage"