apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miladyos-home-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn-single-replica
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn-single-replica
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miladyos-kube-config-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: longhorn-single-replica
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miladyos-pachyderm-config-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: longhorn-single-replica
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-storage-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn-single-replica