apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miladyos-home-pvc
  namespace: miladyos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data-pvc
  namespace: miladyos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miladyos-kube-config-pvc
  namespace: miladyos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miladyos-pachyderm-config-pvc
  namespace: miladyos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-storage-pvc
  namespace: miladyos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
