apiVersion: v1
kind: Namespace
metadata:
  name: kraken
  labels:
    app.kubernetes.io/name: kraken
    app.kubernetes.io/part-of: miladyos
    app.kubernetes.io/managed-by: argocd
    nebula.mesh/enabled: "true"
    milady.mesh/p2p-registry: "true"
  annotations:
    nebula.mesh/network: "192.168.5.0/24"
    avahi.mesh/discovery: "_kraken._tcp"