apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-postgres-pvc
  namespace: mattermost
  labels:
    app.kubernetes.io/name: mattermost-postgres
    app.kubernetes.io/part-of: miladyos
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
