name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver: docker
        driver-opts: |
          image=moby/buildkit:buildx-stable-1
          network=host

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push (direct method)
      if: github.event_name != 'pull_request'
      run: |
        # Build directly from the checked out code
        echo "Building from local checkout instead of GitHub URL"
        docker buildx build \
          --platform linux/amd64 \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/miladyos:latest \
          --push \
          .

    - name: Build without pushing (PR)
      if: github.event_name == 'pull_request'
      run: |
        # Build directly from the checked out code but don't push for PRs
        echo "Building from local checkout (PR - no push)"
        docker buildx build \
          --platform linux/amd64 \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/miladyos:pr-test \
          .

    - name: Logout of Docker Hub
      run: docker logout